NOT MERGE Ai evolutionary
qwrtln/Homm3BG-mission-book pull request #64
Opened 2024-07-18 19:37 UTC by invoceusse

Need one scenario for can use it.

![image](https://github.com/user-attachments/assets/f36db0ea-db0b-425c-b40d-1592d9159756)
![image](https://github.com/user-attachments/assets/7a87b51f-971d-440b-89d7-823b8418767b)
![image](https://github.com/user-attachments/assets/43e77b0d-2af2-4fc5-9db0-549db8eb05e1)
![image](https://github.com/user-attachments/assets/8d7d2573-61f7-4d23-a936-ef1bd47cbf3e)

2024-08-28 18:47 UTC, invoceusse commented
po4a check

2024-08-28 19:52 UTC, qwrtln commented on po4a.cfg
> +[type: latex] coops/ai_evolutionary.tex $lang:coops/translated/$lang/emerald_island.tex opt:"-o verbatim=multicols*,multicols,tikzpicture,scriptsize"
```suggestion
```

2024-08-28 19:52 UTC, qwrtln commented on coops/main.tex
> +
```suggestion
```

2024-08-29 15:41 UTC, qwrtln requested changes
A couple of general remarks:
1. Please make the first page two-columnar. The excess whitespace can be filled with art later.
2. Don't create a separate `ai` directory within `assets`. Please create `skills`, `spells` and `cards` directory. Move all the images to their respective folders with appropriate names, so that `assets/ai/skills/skill_1.png` becomes `assets/skills/air_magic.png`.
3. Make sure that all the table cells and headers text start with a capitalized letter.
4. Some of the sentences are rather hard to comprehend. I suggest using an AI tool like ChatGPT to help you rephrase them to sound more natural. Please use it on every paragraph.

2025-05-10 10:20 UTC, closed without merging